// This file is generated by database/migrations/setup.ts. Do not modify it manually.
// Last updated 2025-11-06 04:20:32

import { extraction_cache } from "./extraction_cache.ts";

export type DatabaseSchema = {
    extraction_cache: extraction_cache
};
