// This file is generated by database/migrations/setup.ts. Do not modify it manually.
// Last updated 2025-11-06 04:20:32

export interface extraction_cache {
    id: string;
    session_id: string;
    file_hash: string;
    extraction_key: string;
    extracted_data: string;
}
